<?php

/**
 * This is the model class for table "blog_posts".
 *
 * The followings are the available columns in table 'blog_posts':
 * @property integer $id
 * @property string $title
 * @property string $small
 * @property string $full
 * @property integer $author
 * @property integer $create_date
 *
 * The followings are the available model relations:
 * @property BlogComments[] $blogComments
 */
class BlogPosts extends EActiveRecord
{
	const PAGE_SIZE = 3;
    /**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'blog_posts';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('author, create_date', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('small, full', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title, small, full, author, create_date', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'blogComments' => array(self::HAS_MANY, 'BlogComments', 'post_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
			'small' => 'Small',
			'full' => 'Full',
			'author' => 'Author',
			'create_date' => 'Create Date',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('small',$this->small,true);
		$criteria->compare('full',$this->full,true);
		$criteria->compare('author',$this->author);
		$criteria->compare('create_date',$this->create_date);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function post(BlogPosts $post)
    {
        $criteria = new CDbCriteria();
        $criteria->compare('post_id', $post->id);
        $this->getDbCriteria()->mergeWith($criteria);
        return $this;
    }


    public function page($currentPage)
    {
        $criteria = new CDbCriteria();
        $criteria->limit = self::PAGE_SIZE;
        $criteria->offset = ($currentPage - 1) * self::PAGE_SIZE;
        $this->getDbCriteria()->mergeWith($criteria);
        return $this;
    }

    public function beforeSave()
    {
        if ($this->isNewRecord) {
            $this->create_date = time();
            $this->author = Yii::app()->user->id;
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }


    /**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return BlogPosts the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}
